# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/11148/Desktop/jizu/09_CPU_Interrupt/Data_RAM/Data_RAM.xci
# IP: The module: 'Data_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/11148/Desktop/jizu/09_CPU_Interrupt/Data_RAM/Data_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_RAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/11148/Desktop/jizu/09_CPU_Interrupt/Data_RAM/Data_RAM.xci
# IP: The module: 'Data_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/11148/Desktop/jizu/09_CPU_Interrupt/Data_RAM/Data_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
